In [ ]:
# CONDE AJURURO CRISTHIAN CI:9895070
# Importando las librerias en Python
import numpy as np
import pandas as pd

In [ ]:
# Importación de datos de la base de datos:
customer_data = pd.read_csv('/content/drive/MyDrive/Employee.csv')
customer_data


Education  JoiningYear  ... ExperienceInCurrentDomain  LeaveOrNot
0     Bachelors         2017  ...                         0           0
1     Bachelors         2013  ...                         3           1
2     Bachelors         2014  ...                         2           0
3       Masters         2016  ...                         5           1
4       Masters         2017  ...                         2           1
...         ...          ...  ...                       ...         ...
4648  Bachelors         2013  ...                         4           0
4649    Masters         2013  ...                         2           1
4650    Masters         2018  ...                         5           1
4651  Bachelors         2012  ...                         2           0
4652  Bachelors         2015  ...                         4           0

[4653 rows x 9 columns]

In [ ]:
# Seleccionamos las variables independientes (columnas) que nos vayan a servir
X = dataset.iloc[:,0:8].values
X

array([['Bachelors', 2017, 'Bangalore', ..., 'Male', 'No', 0],
       ['Bachelors', 2013, 'Pune', ..., 'Female', 'No', 3],
       ['Bachelors', 2014, 'New Delhi', ..., 'Female', 'No', 2],
       ...,
       ['Masters', 2018, 'New Delhi', ..., 'Male', 'No', 5],
       ['Bachelors', 2012, 'Bangalore', ..., 'Male', 'Yes', 2],
       ['Bachelors', 2015, 'Bangalore', ..., 'Male', 'Yes', 4]],
      dtype=object)

In [ ]:
# SEleccionar la variable dependiente
y = dataset.iloc[:,8].values
y

array([0, 1, 0, ..., 1, 0, 0])

In [ ]:
# Codificación de datos categóricos
# Codificación de las variables independientes
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer
# Categorizamos los genero, codificados por números
labelencoder_X_1 = LabelEncoder()
X[:, 5] = labelencoder_X_1.fit_transform(X[:, 5])
X[1]


array(['Bachelors', 2013, 'Pune', 1, 28, 0, 'No', 3], dtype=object)

In [ ]:
# Categorizamos los 'EverBenched', codificados por números
labelencoder_X_2 = LabelEncoder()
X[:, 6] = labelencoder_X_2.fit_transform(X[:, 6])
X[1]

array(['Bachelors', 2013, 'Pune', 1, 28, 0, 0, 3], dtype=object)

In [ ]:
# Categorizamos 'Education', codificados por números
labelencoder_X_3 = LabelEncoder()
X[:, 0] = labelencoder_X_3.fit_transform(X[:, 0])
X[1]

array([0, 2013, 'Pune', 1, 28, 0, 0, 3], dtype=object)

In [ ]:
# Categorizamos 'city', codificados por números
labelencoder_X_4 = LabelEncoder()
X[:, 2] = labelencoder_X_4.fit_transform(X[:, 2])
X[1]

array([0, 2013, 2, 1, 28, 0, 0, 3], dtype=object)

In [ ]:
# OneHotEncoder codifica características enteras categóricas como una matriz numérica one-hot
onehotencoder = ColumnTransformer([("Education", OneHotEncoder(), [0])], remainder = 'passthrough')
X = np.array(onehotencoder.fit_transform(X))
X[1]

array([1.0, 0.0, 0.0, 2013, 2, 1, 28, 0, 0, 3], dtype=object)

In [ ]:
# Eliminar la variable ficticia que hemos creado
X = X[:,1:]
X[1]

array([0.0, 0.0, 2013, 2, 1, 28, 0, 0, 3], dtype=object)

In [ ]:
onehotencoder = ColumnTransformer([("City", OneHotEncoder(), [3])], remainder = 'passthrough')
X = np.array(onehotencoder.fit_transform(X))
X[1]

array([0.0, 0.0, 1.0, 0.0, 0.0, 2013, 1, 28, 0, 0, 3], dtype=object)

In [ ]:
# Eliminar la variable ficticia que hemos creado
X = X[:,1:]
X[1]

array([0.0, 1.0, 0.0, 0.0, 2013, 1, 28, 0, 0, 3], dtype=object)

In [ ]:
# Dividir el conjunto de datos en el conjunto de entrenamiento y pruebas
from sklearn.model_selection import train_test_split
# Dedicar 20% datos a la prueba y el restante al entrenamiento
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 0)

In [ ]:
# Escalado de Categorias
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
X_test

array([[-0.56966847, -0.61082147, -0.48150357, ...,  0.8145134 ,
        -0.34028382,  0.06528154],
       [-0.56966847,  1.63713958, -0.48150357, ..., -1.22772689,
        -0.34028382,  0.06528154],
       [-0.56966847, -0.61082147, -0.48150357, ..., -1.22772689,
        -0.34028382,  0.06528154],
       ...,
       [-0.56966847,  1.63713958, -0.48150357, ...,  0.8145134 ,
        -0.34028382,  1.34229044],
       [ 1.75540697, -0.61082147, -0.48150357, ..., -1.22772689,
        -0.34028382, -0.57322291],
       [-0.56966847,  1.63713958, -0.48150357, ...,  0.8145134 ,
        -0.34028382,  1.34229044]])

In [ ]:
# importando librerias y paquetes de Keras
# Sequential ayuda a iniciarlizar la red neuronal
# Dense ayuda a agregar capas ocultas en nuestra red
import keras
from keras.models import Sequential
from keras.layers import Dense

In [ ]:
# Inicializar la Red Neuronal, definiendo como una secuencia de capas
clasificador = Sequential()

In [ ]:
# Agregando Capa input y Primero Capa Oculta
# units son la cantidad de nodos que se desean agregar (e.g. puede ser la suma de los nodos de ingreso y salida).
# kernel_initializer es el Paso 1, de tipo distribución uniforme
# activation o Función de activación de tipo rectificante = relu
# input_dim crea la capa de ingreso, en este caso 11 columnas
clasificador.add(Dense(units=6, kernel_initializer='uniform', activation='relu', input_dim=10))

In [ ]:
# Agregando segunda capa oculta
clasificador.add(Dense(units=10, kernel_initializer='uniform', activation='relu'))

In [ ]:
# Agregando Capa de Salida con Función de Activación Sigmoide
clasificador.add(Dense(units=1, kernel_initializer='uniform', activation='sigmoid'))

In [ ]:
# Aplicamos el Descenso de Gradiente Estocástica, significa Compilar Red Neuronal.
# optimazer permite definir el algorimo de descenso de gradiente.
# loss es el margen de error "C". En redes convulucionales entendemos como "Binary CrossEntropy" o Entropia Cruzada.
# binary_crossentropy para una salida (Verdadero o Falso), para varios resultados usamos categorical_crossentropy
# metric es el criterio para evaluar el modelo, 
clasificador.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [ ]:
# Ajustamos Red Neuronal en el Set de Entrenamiento
# batch_size es el número de ejemplos por gradiente actualizable.
clasificador.fit(X_train, y_train, batch_size=10, epochs=300)

Epoch 1/300
326/326 [==============================] - 1s 2ms/step - loss: 0.6191 - accuracy: 0.6727
Epoch 2/300
326/326 [==============================] - 1s 2ms/step - loss: 0.5474 - accuracy: 0.7375
Epoch 3/300
326/326 [==============================] - 1s 2ms/step - loss: 0.5263 - accuracy: 0.7396
Epoch 4/300
326/326 [==============================] - 1s 2ms/step - loss: 0.5133 - accuracy: 0.7458
Epoch 5/300
326/326 [==============================] - 1s 2ms/step - loss: 0.5029 - accuracy: 0.7492
Epoch 6/300
326/326 [==============================] - 1s 2ms/step - loss: 0.4941 - accuracy: 0.7660
Epoch 7/300
326/326 [==============================] - 1s 2ms/step - loss: 0.4871 - accuracy: 0.7756
Epoch 8/300
326/326 [==============================] - 1s 2ms/step - loss: 0.4790 - accuracy: 0.7881
Epoch 9/300
326/326 [==============================] - 1s 2ms/step - loss: 0.4699 - accuracy: 0.8007
Epoch 10/300
326/326 [==============================] - 1s 2ms/step - loss: 0.4640 - accura

In [ ]:
# Prediciendo Set de Pruebas
y_pred = clasificador.predict(X_test)
y_pred

array([[0.16112214],
       [0.99976045],
       [0.18549255],
       ...,
       [0.02342138],
       [0.14750418],
       [0.04132107]], dtype=float32)

In [ ]:
y_pred = (y_pred>0.5)
y_pred

array([[False],
       [ True],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [ ]:
# Matri de Confusión: Resumen de los resultados de la predicción del problema de clasificación del modelo.
from sklearn.metrics import confusion_matrix
mc = confusion_matrix(y_test, y_pred)
mc
# ¿que quieren decir estos resultado?

array([[847,  75],
       [159, 315]])

In [ ]:

ac=(847 +315)/(847 +315+75+159)
print(ac)
print("este es el 'acurracy' del modelo")
# CONDE AJURURO CRISTHIAN CI:9895070

0.832378223495702
este es el 'acurracy' del modelo
