In [ ]:
from google.colab import drive
drive.mount('/content/drive')


Mounted at /content/drive


In [ ]:
import numpy as np
import pandas as pd
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split


In [ ]:
#Cargando el archivo
data=pd.read_csv('/content/drive/MyDrive/Copia de default.csv')
data

default student      balance       income
0           0      No   729.526495  44361.62507
1           0     Yes   817.180407  12106.13470
2           0      No  1073.549164  31767.13895
3           0      No   529.250605  35704.49394
4           0      No   785.655883  38463.49588
...       ...     ...          ...          ...
9995        0      No   711.555020  52992.37891
9996        0      No   757.962918  19660.72177
9997        0      No   845.411989  58636.15698
9998        0      No  1569.009053  36669.11236
9999        0     Yes   200.922183  16862.95232

[10000 rows x 4 columns]

In [ ]:
# Reconfigurando la estructura convirtiendo texto en  número
data=data.replace(to_replace='Yes', value=1)
data=data.replace(to_replace='No',value=0)
data


default  student      balance       income
0           0        0   729.526495  44361.62507
1           0        1   817.180407  12106.13470
2           0        0  1073.549164  31767.13895
3           0        0   529.250605  35704.49394
4           0        0   785.655883  38463.49588
...       ...      ...          ...          ...
9995        0        0   711.555020  52992.37891
9996        0        0   757.962918  19660.72177
9997        0        0   845.411989  58636.15698
9998        0        0  1569.009053  36669.11236
9999        0        1   200.922183  16862.95232

[10000 rows x 4 columns]

In [ ]:
# Reconfigurando la estructura del data
y=data['default'].values.reshape(-1,1)
x=data[['balance','income','student']].values.reshape(-1,3)

print('x=',x.shape)
print('y=',y.shape)

x= (10000, 3)
y= (10000, 1)


In [ ]:
#realizar el muestreo : train=70%  test=30%
train_x,test_x,train_y,test_y=train_test_split(x,y,test_size=0.3,shuffle=True,random_state=10)

print('x_train=', train_x.shape)
print('y_train=', train_y.shape)
print('x_test=', test_x.shape)
print('y_test=', test_y.shape)
train_x

x_train= (7000, 3)
y_train= (7000, 1)
x_test= (3000, 3)
y_test= (3000, 1)


array([[5.17228508e+02, 4.02485861e+04, 0.00000000e+00],
       [2.74194628e+02, 1.54215517e+04, 1.00000000e+00],
       [3.81520969e+02, 3.17507773e+04, 0.00000000e+00],
       ...,
       [1.66368701e+03, 1.98476986e+04, 1.00000000e+00],
       [3.12127697e+02, 3.77435081e+04, 0.00000000e+00],
       [1.14263798e+03, 2.67310904e+04, 0.00000000e+00]])

In [ ]:
#Creamos nuestra red neuronal
ann = MLPClassifier(activation="logistic", solver="sgd", hidden_layer_sizes=(10, 200, 100, 100, 40), random_state=1)
ann.fit(train_x,train_y)
predicciones=ann.predict(test_x)
predicciones

/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:934: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([0, 0, 0, ..., 0, 0, 0])

In [ ]:
#Calculamos la matriz de confusión
from sklearn.metrics import confusion_matrix
tp,fp,fn,tn=confusion_matrix(test_y,predicciones,labels=[1,0]).ravel()

print('TN=',tn)
print('FP=',fp)
print('FN=',fn)
print('TP',tp)
print()
confusion_matrix(test_y,predicciones,labels=[1,0])

TN= 2888
FP= 112
FN= 0
TP 0



array([[   0,  112],
       [   0, 2888]])

In [ ]:
#Calculamos el Accurracy
acc=(tn+tp)/(tn+fp+fn+tp)
print('Accurracy:'+str(acc))

Accurracy:0.9626666666666667


In [ ]:
#Calculanco la sensitividad del modelo
sencitivity=tp/(tp+fn)
print('Sencitivity:'+str(sencitivity))

Sencitivity:nan


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in long_scalars
  


In [ ]:
#Calculanco la Especificidad del modelo
specificity=tn/(tn+fp)
print('Specificity:'+str(specificity))

Specificity:0.9626666666666667
